#!/bin/bash

PROVISIONINGPATH=~/.osx-provisioning

OSX_GITHUB="https://github.com/Nobv/osx-provisioning.git"

info() {
  printf "\e[37;1m%s\e[m\n" "$*"
}

succes() {
  printf "\e[36m%s\e[m\n" "✔ $*"
}

error() {
  printf "\e[31;2m%s\e[m\n" "✖ $*"
}

# Download
download() {

  if [ -d $PROVISIONINGPATH ];then
    error "${PROVISIONINGPATH} is already exists."
    exit 1
  fi

  # TODO: when git is not exists
  info "Downloading provisioning file..."
  git clone "$OSX_GITHUB" $PROVISIONINGPATH

  succes "Download"
}

provisioning() {

  download

  make inisialize

  make install

  make osx_update:
}

succes "Download test!!!!"
